version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/var/www/task-manager

permissions:
  - object: /home/ubuntu/var/www/task-manager
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ubuntu

    - location: scripts/nginx.sh
      timeout: 60
      runas: ubuntu

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: ubuntu
