version: 0.3

phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - echo Installing dependencies...
      - composer install --no-interaction --optimize-autoloader
  pre_build:
    commands:
      - echo Executing pre-build phase...
  build:
    commands:
      - echo Executing build phase...
  post_build:
    commands:
      - echo Executing post-build phase...

artifacts:
  files:
    - "**/*"
