version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - composer install --no-interaction --optimize-autoloader
  build:
    commands:
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
